name: Deploy Groceries

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Create the env file
      run: |
        touch env.js
        echo 'module.exports = credendials = { production: { api: "${{ secrets.PRODUCTION_API_LINK }}" } }' >> env.js
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: 22
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "dist/"
        target: ${{ secrets.REMOTE_TARGET }}