name: Deploy Groceries

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v1
    # - name: Install Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '14.x'
    # - name: Create the env file
    #   run: |
    #     touch env.js
    #     echo 'module.exports = credendials = { production: { api: "${{ secrets.PRODUCTION_API_LINK }}" } }' >> env.js
    # - name: Install npm dependencies
    #   run: npm install
    # - name: Run build task
    #   run: npm run build
    - name: Prepare SSH to work with the remote server
      run: |
        echo '${{ secrets.SERVER_SSH_KEY }}' >> private_key
        ssh -i private_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
    # - name: Deploy to Server
    #   uses: easingthemes/ssh-deploy@main
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    #     ARGS: "-rltgoDzvO --delete"
    #     SOURCE: "images/"
    #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #     TARGET: ${{ secrets.REMOTE_TARGET }}
    #     EXCLUDE: "/node_modules/"
